module.exports.run = async(client, message, args) => {
    if (message.content === "r!burro") {
         message.channel.send('BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO BURRO');
     } 
    };
 