module.exports.run = async(client, message, args) => {
    if (message.content === "r!freefas") {
         message.channel.send('FALA DO MEU FREE FIRE DNV CARA 🤬🤬🤬😎👊👊🥇💪 SE VC TIVE CORAGEM 🤬😡🤫 FALA NA MINHA CARA MAIS GRITA ALTO PRA EU OUVI PQ SE VOCE FALA BAXO EU NAO VO ESCUTA PQ NAO VAI TA SENDO VERDADE PQ O FREE FIRE É O MELHOR JOGO JA FEITO PELO MUNDO INTEIRO 😍❤ELE ATE FOI ELEITO O MELHOR BATTLE ROYALE DE 2018 🏆🥇 NA PLAYSTORE OK? ENTAO PENSA 😎😎😎 MELHOR ANTES DE FALA DO MEU FREE FIRE SE NAO EU TE MATO TA BOM 👊👊💪👣 ? TABOM ? TE MATO Ó AQUI Ó Ó 🥵🤯🤬 TE MATO MESMO VIU? 😎😎😎👣🤬🤬');
     } 
    };
 