module.exports.run = async(client, message, args) => {
    if (message.content === "r!japa") {
         message.channel.send('TU E MONGOL FILHO(A) DA PUTA? TU ME ADICIONA COM UM NOME NORMAL, DAI EU VIRO TEU AMIGO, PAPO VAI PAPO VEM E DO NADA TU MUDA TEUS NOME NA REDE SOCIAL E COLOCA UM NOME JAPONÊS FUDIDO? VAI TOMAR NO CU SEU ARROMBADO REPARA QUE EU E VOCE TODO MUNDO AQUI QUE VIVE NO BRASIL E BRASILEIRO SEU FILHO DA PUTA ENFIA ESSE NOME JAPONÊS NO SEU CU, JUNTO COM ESSA FOTO DE ANIME CARALHO, ISSO AI E COISA DE MONGOL, COISA DE BAITOLA, SE TU QUERIA FAZER ISSO NAO ERA NEM PRA TER ME ADICIONADO NESSA MERDA, UMA VEZ FUI TE MARCAR NUM BAGULHO, FUI ESCREVER TEU NOME FUDIDO EM JAPONÊS E ACABEI MARCANDO A BANDA DE BTS TODINHA NO MEU COMENTÁRIO, ISSO TUDO POR CAUSA DE VOCÊ SEU FILHO DA PUTA.');
     } 
    };
 